### ISSUE TITLE
Do not use the umn/hgcroc branch for ldmx-sw

### ISSUE THREAD

**Issue by cjfroemming** [tomeichlersmith/ldmx-cob#4]
If you try to use the `umn/hgcroc` branch on the [ldmx-sw](https://github.com/LDMX-Software/ldmx-sw) repository, then you will get the following error while trying to run the command `ldmx fire decode.py <some file>.raw`:

> Traceback (most recent call last):
> File "/home/froem073/ldmx/cob/decode.py", line 57, in <module>
> dqm.NtuplizeHgcrocDigiCollection(
> AttributeError: module 'LDMX.DQM.dqm' has no attribute 'NtuplizeHgcrocDigiCollection'
> Configuration Error [ConfigureError] : Problem loading python script
> at /home/froem073/ldmx/ldmx-sw/Framework/src/Framework/ConfigurePython.cxx:201 in ConfigurePython
> Stack trace: 
> 0 framework::ConfigurePython::ConfigurePython(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char**, int) + 1982 
> 1 main + 323 addr2line: 'fire': No such file

The fix was switching to the `trunk` repository, where the `/ldmx/DQM/dqm.py` file the attribute `NtuplizeHgcrocDigiCollection`. I believe the current setup docs recommend using `umn/hgcroc`, so they should either be changed, or have the `umn/hgcroc` branch be updated sufficiently.

**Comment by tomeichlersmith** [comment]
Thank you for figuring this out, I've updated the notes/decode.md file to reflect this update.
